### ISSUE TITLE
iisignature import error when trying to use esig==0.9.4

### ISSUE THREAD

**Issue by jambo6** [datasig-ac-uk/esig#100]
Hi! I'm receiving the following error when I try to import esig using the 0.94 install. 

My version of numpy is 1.1.9, the traceback is below.

```
Traceback:
../../../../hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/esig/backends.py:18: in <module>
    import iisignature
E   ModuleNotFoundError: No module named 'iisignature'

During handling of the above exception, another exception occurred:
../../../../hostedtoolcache/Python/3.7.10/x64/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
../../../../hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/sktime/transformations/tests/test_all_transformers.py:24: in <module>
    ALL_TRANSFORMERS = all_estimators(estimator_types="transformer", return_names=False)
../../../../hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/sktime/utils/__init__.py:98: in all_estimators
    module = import_module(module_name)
../../../../hostedtoolcache/Python/3.7.10/x64/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
../../../../hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/sktime/classification/signature_based/__init__.py:4: in <module>
    from sktime.classification.signature_based._signature_classifier import (
../../../../hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/sktime/classification/signature_based/_signature_classifier.py:17: in <module>
    from sktime.transformations.panel.signature_based._checks import (
../../../../hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/sktime/transformations/panel/signature_based/__init__.py:6: in <module>
    from sktime.transformations.panel.signature_based._signature_method import (
../../../../hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/sktime/transformations/panel/signature_based/_signature_method.py:4: in <module>
    from sktime.transformations.panel.signature_based._compute import (
../../../../hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/sktime/transformations/panel/signature_based/_compute.py:10: in <module>
    from sktime.transformations.panel.signature_based._rescaling import (
../../../../hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/sktime/transformations/panel/signature_based/_rescaling.py:14: in <module>
    _check_soft_dependencies("esig")
../../../../hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/sktime/utils/validation/_dependencies.py:23: in _check_soft_dependencies
    import_module(package)
../../../../hostedtoolcache/Python/3.7.10/x64/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
../../../../hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/esig/__init__.py:28: in <module>
    from esig.backends import get_backend, set_backend, list_backends
../../../../hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/esig/backends.py:21: in <module>
    raise ImportError("No available backend for signature calculations, please reinstall esig.")
```

**Comment by inakleinbottle** [comment]
Thanks @jambo6. I'm going to try to recreate this on my own system to see if I can figure out what is going wrong.

**Comment by inakleinbottle** [comment]
A quick google search indicates that this might be a problem with pip: https://github.com/pypa/pip/issues/9542. I think what is happening is that the build dependency used in the esig pipeline is unpinned and therefore is building against a later version of Numpy than the one pinned in your repository. If this is the case, then we should pin our build numpy version to the earliest that we want to support, 1.17 or so. I'll keep looking.

**Comment by terrylyons** [comment]
I have a similar problem with version 9.5 tonight; impossible to use esig if iisignature is installed. Remove it and all is fine.

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64>python -m pip uninstall iisignature
Found existing installation: iisignature 0.24
Uninstalling iisignature-0.24:
  Would remove:
    c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\iisignature-0.24.dist-info\*
    c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\iisignature.cp36-win_amd64.pyd
    c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\iisignature_data\*
Proceed (y/n)? y
  Successfully uninstalled iisignature-0.24

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64>python -m pip install iisignature
Collecting iisignature
  Using cached iisignature-0.24-cp36-cp36m-win_amd64.whl (1.4 MB)
Collecting numpy>1.7
  Using cached numpy-1.19.5-cp36-cp36m-win_amd64.whl (13.2 MB)
Installing collected packages: numpy, iisignature
  WARNING: The script f2py.exe is installed in 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed iisignature-0.24 numpy-1.19.5

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64>python -m pip install esig
Collecting esig
  Using cached esig-0.9.5-cp36-cp36m-win_amd64.whl (3.7 MB)
Requirement already satisfied: numpy>=1.7 in c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages (from esig) (1.19.5)
Installing collected packages: esig
Successfully installed esig-0.9.5

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64>python
Python 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import esig
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\esig\__init__.py", line 28, in <module>
    from esig.backends import get_backend, set_backend, list_backends
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\esig\backends.py", line 169, in <module>
    BACKENDS["iisignature"] = IIsignatureBackend
NameError: name 'IIsignatureBackend' is not defined
>>> from esig import tosig
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\esig\__init__.py", line 28, in <module>
    from esig.backends import get_backend, set_backend, list_backends
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\esig\backends.py", line 169, in <module>
    BACKENDS["iisignature"] = IIsignatureBackend
NameError: name 'IIsignatureBackend' is not defined
>>> exit()

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64>python -m pip uninstall iisignature
Found existing installation: iisignature 0.24
Uninstalling iisignature-0.24:
  Would remove:
    c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\iisignature-0.24.dist-info\*
    c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\iisignature.cp36-win_amd64.pyd
    c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\iisignature_data\*
Proceed (y/n)? y
  Successfully uninstalled iisignature-0.24

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64>python
Python 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from esig import tosig
>>>
