### ISSUE TITLE
Error building esig 0.7.2 from source

### ISSUE THREAD

**Issue by wissam124** [datasig-ac-uk/esig#61]
Hi,

I am having trouble building esig 0.7.2 from source

A note on my configuration first:
Python: Python 3.7.4
System: Windows Server 2016 64-Bit
Boost: I have downloaded and installed the precompiled binaries for the latest release of Boost (1.73.0) with compiler msvc 14.2

Once I downloaded and extracted the source from pypi.org, I ran the following command into my shell within the extracted esig directory
```shell
python setup.py install
```
And got the following error trace
```python
c:\Users\jdupin\Documents\Python\lib\site-packages\setuptools\distutils_patch.py:26: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  "Distutils was imported before Setuptools. This usage is discouraged "
Ignoring attempt to add_dll_directory.
esig_install> Starting esig installer...
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from esig import install_helpers as helpers
  File "n:\esig-0.7.2\esig\install_helpers.py", line 932, in <module>
    CONFIGURATION = InstallationConfiguration()
  File "n:\esig-0.7.2\esig\install_helpers.py", line 576, in __init__
    self.__run_checks()
  File "n:\esig-0.7.2\esig\install_helpers.py", line 608, in __run_checks
    ComponentChecker.check_libraries(self.library_dirs)
  File "n:\esig-0.7.2\esig\install_helpers.py", line 774, in library_dirs
    raise "MKLROOT not defined."
TypeError: exceptions must derive from BaseException
```

I wasn't sure why the MKLROOT environment variable is required (do I need to install the Intel Math Kernel library? this is not specified anywhere in the online documentation) so decided to comment the following part of the code (including the expanduser part since this seems to have hardcoded values).
```python
            if not('MKLROOT' in os.environ):
                raise "MKLROOT not defined."
            # not sure why this is only needed on Windows
            return_list.append(os.path.join(os.environ['MKLROOT'], "lib", "intel64"))
            # todo: lose hardcoded knowledge of recombine installation dir
            from os.path import expanduser
            recombine_lib_dir = os.path.join(expanduser("~"), "lyonstech", "lib")
            os.listdir(recombine_lib_dir)
            return_list.append(recombine_lib_dir)
```

Running the setup.py script again now results in the following
```shell
Ignoring attempt to add_dll_directory.
esig_install> Starting esig installer...
esig_install> Required libraries found! Hurrah!
esig_install> Include files successfully found.
running install
running bdist_egg
running egg_info
writing esig.egg-info\PKG-INFO
writing dependency_links to esig.egg-info\dependency_links.txt
writing requirements to esig.egg-info\requires.txt
writing top-level names to esig.egg-info\top_level.txt
reading manifest file 'esig.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
c:\Users\jdupin\Documents\Python\lib\site-packages\setuptools\distutils_patch.py:26: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  "Distutils was imported before Setuptools. This usage is discouraged "
warning: no previously-included files found matching '.DS_Store'
writing manifest file 'esig.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
copying esig\install_helpers.py -> build\lib.win-amd64-3.7\esig
running build_ext
esig_install> Running extra esig pre-build commands...
building 'esig.tosig' extension
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\bin\HostX86\x64\cl.exe /c /nologo
 /Ox /W3 /GL /DNDEBUG /MD -Ic:\Users\jdupin\Documents\Python\include -I.\src\ -I.\libalgebra\ -I.\recombine\ -
I.\build\recombine\recombine\ -IC:\local\boost_1_73_0_14_0 -Ic:\Users\jdupin\Documents\Python\include -
Ic:\Users\jdupin\Documents\Python\include -Ic:\Users\jdupin\Documents\Python\lib\site-packages\numpy\core\include "-
IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\include" "-IC:\Program Files 
(x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-
IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows 
Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files 
(x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tcsrc/C_tosig.c /Fobuild\temp.win-amd64-3.7\Release\src/C_tosig.obj 
/EHsc /DWINVER=0x0601 /D_WIN32_WINNT=0x0601 /D_SCL_SECURE_NO_WARNINGS /bigobj
C_tosig.c
src/C_tosig.c(16): fatal error C1083: Cannot open include file: '_recombine.h': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
```

I cannot find a '_recombine.h' file in the recombine folder.
Note that I have also tried using directly the most recent commit from the esig github repo which does include a _recombine.h file. The install fails again with this time the script looking also for a /recombine/recombine.h file which doesn't seem to be present.

Thanks

**Comment by rolyp** [comment]
Tagged as Documentation for now.

**Comment by rolyp** [comment]
`MKLROOT` no longer needs to be defined.
